### PR TITLE
Update `yn_to_tf()` to have a more robust regex

### PR DESCRIPTION
**Pull request by mstackhouse**
This update focuses on #47. The `yn_to_tf()` function wasn't fully tolerant to possibilities of yes/no formatting, so this updates the regex to ignore case sensitivity and better check formatting. 

A main part of the update was moving from single string regexes to using `regex("expr", ignore_case = T).

### CODE REVIEW

**Comment by mstackhouse** [comment]
@statasaurus - within the spec readers in general, For hte column pattern matching, I think for the most part it would be much cleaner to ignore case rather than explicitly check for capitalization. What do you think?

**Review by statasaurus — APPROVED** [review]
Looks great! Yeah I agree it makes more sense to just add the other options rather than making it too loose. I think if we go too far the behaviour could get a bit unpredictable. 🌟

**Comment by statasaurus** [comment]
If you are feeling super cool could you add the fix to the news file? I don't think this change is big enough to make it worth submitting to CRAN again, but it will be helpful to have it recorded so when we do submit we remember we changed this.

**Comment by mstackhouse** [comment]
> If you are feeling super cool could you add the fix to the news file? I don't think this change is big enough to make it worth submitting to CRAN again, but it will be helpful to have it recorded so when we do submit we remember we changed this.

Updated that for you. I slated it under 0.0.5 within the news, but I set the package version to 0.0.4.9001 as the dev version so just let me know if you want that handled any differently.

**Pull request merged**
