### PR TITLE
Many mini fixes

### PR DESCRIPTION
**Pull request by statasaurus**
This will fix almost all the current issues. None of which were huge so I didn't feel like they justified their own branch. 

- #16 the metacore function now accepts any empty datasets and creates an empty dataset with the correct column names and types
- #10 yn function checks for logicals and returns them 
- #11 updated function description to make this clearer
- #12 updated regex so to [F|f]ormat so it can accept lower case
- #14 added supp_flag to ds_vars (on a side note we did a really good job with this it was super easy to change and only required a few edits)
- #15 modified create =tbl so if there are two potential matches in the same dataset and one is an exact match it uses that 

Once this is merged in do you want to submit to CRAN? it will probably fail, but it will give us another bolus of issues to tackle

### CODE REVIEW

**Comment by mstackhouse** [comment]
@statasaurus I'd like to try to fix the failures for R 3.5 and 3.6. Have you looked into those at all?

**Comment by mstackhouse** [comment]
@kodesiba since you and Christina discussed a lot of these changes, could you check out these updates? 

@statasaurus can you add a NEWS.md file so we can throw the changelog up on the pkgdown too?

**Comment by statasaurus** [comment]
> 

I didn't see an issue for this? Is it somewhere to look at?

**Comment by mstackhouse** [comment]
@statasaurus see [here](https://github.com/atorus-research/metacore/issues/19). Any time we merge with main we should update this and the version.

**Comment by statasaurus** [comment]
@kodesiba can you review this now? It is passing all the checks it should and I have added a news page

**Review by mstackhouse — APPROVED** [review]

**Comment by kodesiba** [comment]
@statasaurus @mstackhouse everything here looks good to me. Super excited with these changes!

**Pull request merged**
